 "<tr> "
+ "                                   <th scope='row'><b>#122349</b></th> "
 + "                                  <td> "
  + "                                     <div class='tm-status-circle moving'> "
   + "                                    </div>Moving  "
    + "                               </td> "
     + "                              <td><b>Oliver Trag</b></td> "
      + "                             <td><b>London, UK</b></td> "
      +  "                            <td><b>485 km</b></td> "
       +  "                           <td>16:00, 12 NOV 2018</td> "
        +  "                          <td>08:00, 18 NOV 2018</td>  "
         +  "                     </tr>   "